### ISSUE TITLE
Improve the cache system

### ISSUE THREAD

**Issue by DanChaltiel** [DanChaltiel/autoimport#18]
As of now, the cache system is at the file level: 

- Each file has its `digest::digest()` hash saved
- The whole file won't be parsed again if it hasn't changed

## TODO

In `autoimport_parse()` mostly.

- [x] add a reference (=function) level of caching, so that if the file has changed, only the functions that have changed are parsed
- [x] use internal cache (in `inst/` maybe?) by default, with`use_cache="temp"` for temporary (current default)
- [x] try simplifying the file organization into one single `.rds` file (`cache_dir` -> `cache_file`)
- [x] try replacing `digest()` by `tools::md5sum()` to avoid an import.
